language: node_js
node_js:
  - node
deploy:
  provider: heroku
  api_key:
    secure: cQGnhxDKxRtQHBLzUBnEgRtLzC1hDLPHiEOgNiGnTivO6w4CgvqUj6nzDKxAyRr2m0U1VHQZLkfYLA835Msf7y66O9iWIfHO8rmgcAHPuXWMgrpuJSVvwm7LpFJfH+uKzfbUVP0HF2Fw8eoBa0NrU4i3Fc/UcfEyixOMTbIh8e4UP979ES9fznI3D0esve6pq/IHsE0jibItzGE0p0b3dQ4+jSYCgz6R6SWVYUZmYKN+nfOwrlq0bI33FT0qLahx+8vZP1QnXDqITqqddwmEPL4zEHkce6EP+Oxu8s34VgaB1CoM84foxw72v76gtZq9oZPVxVaQkbXk7LeH1rXQg5cYIWXDIc6/vgVjseCtMDvmEshuEDoS83uPXy1u36PapxrDaC+HXodbvWR2Jh2zDBimY12XQhYAVpkTjvI8wTVYnBlh2ssVDsPPX7gAQwpXY0Wa1PBN/j/74nvRValL9TjRXtPofTaFZlkvaL5rCbpT5Jns25pd0LQVgMYZsyGRz2WJBBVM19O0XLnzFbrHlvi2Nt9BlkHbbjd91cfpA/P/n1gaYmqJNC1OtIZ6nbr04038N5bD2ItCBPNElz4u3FYiUNEe33qcEvquFZsMm4OC8wYZ+iNDJLIePsRFpFj2nD10c7OtDvceD9XxWeB0v3ZYk0ocEbjiwRjyYNNX7n8=
  app: eruditor-next
  on:
    repo: armagames/eruditor-next-api
