language: node_js
node_js:
  - node
deploy:
  provider: heroku
  api_key:
    secure: S0kY2+jWGHOfgjiR4/uphGxVcHFgnmFVkPOdcrD6FWJ3y5T6KUzMCayjY+0aO7ik7ppdG83U06/1WhZyA63OAYJg4iGPdOvf5FBOjCm0h48z/yjTD2xJatFVvi8aFLXDqpF7iqgTo14DadwuFJekusWgyvouHV522E7Y0yrG65+1wHQ8RYTZRQ7WCPndR7gRYDyU9fg05ptoC5omdWdb+xJy+r640wD56cUHo9t72qVFNUAiuhdDxXBEDC0Zxh+BiccAy47/sNFNI6g1uMZ5BuDbJzwWu3fLELo1EdjJs5/iXaueL246xwQzR0zaVYE26SyDdin1+W2vVAgBAgx6048yRLwXaFwoVdYw3slsBv7ApChDUxjUQrdXDDE7UVAwo5xKTeUo4lMfXVKSUCvvjJiTbaGCX43HbFh6rdW9NtFRFpQ4e0vG5mOWO9pzO3x9duvIxlsB6P7h4u/sujqTFk3ogxVO26HEPsf1hfCazGlzecMPoa1dKA1usguDP2M/BL8/Jaw2KOHOGgJBTqXfsXRyTpl5K3AmLAHWh564dDOi4QHn4ysstAzPjISKGnvmQ1I38HX7kqiykevqpbjSRCF5WY9iNq/fwgC0WxV1k9/ieCWWMp62h8fHwhbvF6rGjYwGCwG6eARjE5SKJYwLSl0lG/QxPRw0WNWtxpOLZAI=
  app: eruditor-next-api
  on:
    repo: armagames/eruditor-next-api
